name: Train ML Model with MLflow

on:
  push:
    paths:
      - 'MLProject/**'
      - '.github/workflows/**'

jobs:
  train-model:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Install Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: 3.9
          environment-file: MLProject/conda.yaml
          activate-environment: mlflow-env  # Sesuaikan dengan nama env di conda.yaml

      - name: Run MLflow Project
        shell: bash -l {0}  # penting! agar conda env dikenali
        run: |
          cd MLProject
          mlflow run . -P alpha=0.5

      - name: Upload artifact to Google Drive
        run: echo "Simulasi upload ke Google Drive" # trigger workflow lagi
